title: VTEX Store Block course
tagline: Learn how to create custom blocks on VTEX Store Framework
description: 'Using React and Graphql, you can export your components as VTEX blocks'
template:
  name: store-block
  repo: store-block-template
preferences:
  - type: dropdown
    name: language
    label: Language
    description: Choose your preferred language.
    options:
      - label: English
        value: en
      - label: Português
        value: pt
before:
  - body: 01_manifest.md
    title: Custom blocks course
    type: createIssue
steps:
  - title: Custom blocks course
    description: >-
      In this step, you'll learn how an app's files are organized in VTEX IO and
      what each field of the manifest.json means
    translations:
      pt:
        title: Curso de blocos customizados
        description: >-
          Neste passo, você irá aprender como se organizam os arquivos em uma
          app VTEX IO e o que cada campo no manifest.json significa
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        with: congrats_course.md
